#!/bin/bash -e

if [ ! -n "$1" ];then
    echo "Usage: createlib [lib name]"
    exit 1
fi

name=$1

git clone https://github.com/duinodu/samplemod $name

cd $name
rm -rf .git 

libname=`echo $name | sed -e 's/-/_/g'`
mv sample $libname

year=`date +"%Y"`
user=`whoami`

sed -i -e "s/samplemod/${libname}/g" setup.py
sed -i -e "s/sample/${libname}/g" tests/context.py 
sed -i -e "s/sample/${libname}/g" tests/test_basic.py
sed -i -e "s/sample/${libname}/g" \
       -e "s/USER/${user}/g" \
       -e "s/YEAR/${year}/g" \
    docs/conf.py 
sed -i -e "s/sample/${libname}/g" docs/index.rst
sed -i -e "s/sample/${libname}/g" Makefile

git init
git add .
git commit -m 'init'
