#!/bin/bash

if [ ! -n "$1" ];then
    echo "createmod [hobot-framework module name]"
    exit 1
fi

mod=$1
MOD=`echo $mod | tr '[:lower:]' '[:upper:]'`
user=min.du
date_str=`date +%m/%d/%Y`
year=`date +%Y`
script=$(realpath $0)
root=$(dirname $script)

cp $root/_template/hobotsdk_module.h ${mod}.h
cp $root/_template/hobotsdk_module.c ${mod}.c


sed -e "s/%MOD%/${MOD}/g" \
    -e "s/%mod%/${mod}/g" \
    -e "s/%user%/${user}/g" \
    -e "s#%date%#${date_str}#g" \
    -e "s/%year%/${year}/g" \
    -i ${mod}.h

sed -e "s/%mod%/${mod}/g" \
    -e "s/%user%/${user}/g" \
    -e "s#%date%#${date_str}#g" \
    -e "s/%year%/${year}/g" \
    -i ${mod}.c
