#!/bin/bash

#find . | xargs grep $1 -r
grep -rnw . -e "$1" --color=always --binary-file=without-match $*

read -p "replace with ? [target str, or 'Enter' to skip] " answer
if [[ $answer = "" ]]; then
    exit
else
    sed -i "s/$1/$answer/g" `grep -rl . -e "$1"`   
fi

grep -rnw . -e "$answer" --color=always --binary-file=without-match $*
