#!/bin/bash

if [ ! -n "$1" ];then
    echo "format-code [python file]"
    exit 1
fi

function py_grep_all() {
    python -c "
items = '$1'.split(' ')
for item in items:
    print(item)
"
}


function add___all___definition() {
    if [[ $(grep -e "^__all__" $1) ]];then
        echo "__all__ already in $1" 
        return
    fi

    OLDIFS=$IFS
    IFS="
"
    result=$(grep  -o -e "^def.*(" -e "^class.*" $1 | cut -d '(' -f1)
    IFS=$OLDIFS
    save_str="__all__ = ["

    if [[ $result ]]; then
        for item in ${result[@]};do
            if [[ $item == *"def"* || $item == *"class"* ]]; then
                continue
            else
                save_str=${save_str}"'${item}', "
            fi
        done
        save_str=${save_str}"]"
        echo $save_str >> $1
    fi
}

add___all___definition $1
