#!/usr/bin/env perl

use strict;

open f, $ENV{'HOME'}."/.gitpullrc" or die "~/.gitpullrc not found";
while (my $line=<f>) {
    chomp $line;
    $line =~ s/~/$ENV{'HOME'}/;
    print "$line\n";
    chdir($line) or die "can't cd to ".$line;
    system "git pull";
    print "\n";
}
close f;
