#!/usr/bin/env perl

use strict;

open f, $ENV{'HOME'}."/.my-gitrc" or die "~/.my-gitrc not found";
while (my $line=<f>) {
    chomp $line;
    $line =~ s/~/$ENV{'HOME'}/;
    print "$line\n";
    chdir($line) or die "can't cd to ".$line;
    system "gits 'what a nice day'";
    print "\n";
}
close f;
