#!/bin/bash

#new_hdfs=hdfs://hobot-bigdata-aliyun/user
hdfs1=hdfs://hobot-bigdata/user
hdfs2=hdfs://hobot-mosdata/user

path=.
if [ -n "$1" ];then
    path=$1
fi

hdfs=$hdfs1
if [ -n "$2" ];then
    hdfs=$hdfs2
fi

user=`whoami`
if [ -n "$3" ];then
    user=$3
fi

echo "hadoop fs -ls $hdfs/$user/$path"
hadoop fs -ls $hdfs/$user/$path 
