#!/bin/bash

hdfs1=hdfs://hobot-bigdata/user
hdfs2=hdfs://hobot-bigdata-aliyun/user

path=.
if [ -n "$1" ];then
    path=$1
fi

hdfs=$hdfs1
if [ -n "$2" ];then
    if [ "$2"x = "ali"x  ];then
        hdfs=$hdfs2
    else
        hdfs=$hdfs1
    fi
fi
echo "use $hdfs"

user=`whoami`
if [ -n "$3" ];then
    user=$3
fi

if [[ $1 == "hdfs"*  ]]; then
    echo "hadoop fs -ls $1"
    hadoop fs -ls $1
else
    echo "hadoop fs -ls $hdfs/$user/$path"
    hadoop fs -ls $hdfs/$user/$path 
fi
