#!/bin/bash

if [ ! -n "$1" ];then
    echo "killme [cmd name]"
    exit 1
fi

PIDs=$(ps ux | grep "$1" | grep -v "grep" | grep -v "killme" | awk '{print $2}')
for pid in ${PIDs[@]};do
    echo "kill $pid"
    kill -9 $pid
    sleep 0.3
done
