#!/bin/bash -ex

if [ ! -L ~/hdfs ];then
    ln -s /opt/hdfs/user/min.du hdfs
fi

cd ~/
if [ ! -d ~/py2 ];then
    virtualenv -p python2 py2
    source ~/py2/bin/activate
    pip install numpy opencv-python enum34 easydict matplotlib ipdb
fi

cp -rf ~/hdfs/code/mxnet-python-xin ~
cp -rf ~/hdfs/code/smart_iot_multitask ~
cp ~/hdfs/code/.profile ~
tar -zxvf ~/hdfs/code/vim.tar.gz -C ~/
cp ~/hdfs/code/.vimrc ~

echo "source ~/.profile" >> ~/.bashrc

echo "please source ~/.profile to config environment"
