#!/bin/bash

if [ $# -eq 0 ]
    then
        echo "Usage: runboost [xxx.cpp]"
        exit 0
fi

g++ $1 -std=c++11 \
-lboost_atomic \
-lboost_chrono \
-lboost_context \
-lboost_coroutine \
-lboost_date_time \
-lboost_filesystem \
-lboost_graph \
-lboost_iostreams \
-lboost_locale \
-lboost_log_setup \
-lboost_log \
-lboost_math_c99f \
-lboost_math_c99l \
-lboost_math_c99 \
-lboost_math_tr1f \
-lboost_math_tr1l \
-lboost_math_tr1 \
-lboost_prg_exec_monitor \
-lboost_program_options \
-lboost_python \
-lboost_random \
-lboost_regex \
-lboost_serialization \
-lboost_signals \
-lboost_system \
-lboost_thread \
-lboost_timer \
-lboost_unit_test_framework \
-lboost_wave \
-lboost_wserialization \
&& ./a.out $2 && rm ./a.out
