#!/bin/sh

if [ ! -n "$1" ];then
    echo "Usage: runlatex xxx.tex."
    exit 1
fi


texname=$1
texname=${texname%.*}
xelatex $texname.tex

if [ ! -n "$2" ];then
    echo "Using bibtex."
    bibtex $texname.aux
    xelatex $texname.tex
fi

evince $texname.pdf
