#!/bin/bash

if [ ! -n "$1" ];then
    echo "runreact [component.js]"
    exit 1
fi

if [ ! -d .runreact ];then
    git clone https://github.com/DuinoDu/runreact
    mv runreact .runreact
fi
cd .runreact
rm .git -rf

if [[ ! -L node_modules && ! -d node_modules ]];then
    if [[ -d ../node_modules ]];then
        ln -s ../node_modules node_modules
    else
        cnpm install
    fi
fi

if [ -d dist ];then
    rm dist -r
fi

cp ../$1 .
copyfile=`basename $1`
filename=${copyfile%.*}
component=`grep '^export' $copyfile | cut -d ' ' -f 3 | cut -d ';' -f 1` 
sed "s/component/${component}/g" index.js.bak > index.js
sed -i "s/file/${filename}/g" index.js

webpack
firefox index.html
