#!/bin/bash -e

cd ~/

if [ ! -f ~/.ssh/id_rsa.pub ];then
    echo "Create id_rsa.pub"
    ssh-keygen -t rsa
fi

read -p "target: [required]" target
if [[ $target = "" ]]; then
    echo "Target no found"
    exit
fi

read -p "username? [option]" username
if [[ $answer = "" ]]; then
    username=`whoami`
    echo "use default username: $username"
fi

sh-copy-id $username@$target
