#!/bin/bash -e
# File              : ssh_wo_password
# Author            : du min <min.du@hobot.cc>
# Date              : 15.08.2018
# Last Modified Date: 15.08.2018
# Last Modified By  : du min <min.du@hobot.cc>

cd ~/

if [ ! -f ~/.ssh/id_rsa.pub ];then
    echo "Create id_rsa.pub"
    ssh-keygen -t rsa
fi

read -p "target: [required]" target
if [[ $target = "" ]]; then
    echo "Target no found"
    exit
fi

read -p "username? [option]" username
if [[ $username = "" ]]; then
    username=`whoami`
    echo "use default username: $username"
fi

ssh-copy-id $username@$target
