#!/bin/bash

if [ ! -n "$1" ];then
    echo "start-paper-coding [paper name]"
    exit 1
fi

if [ -d $1 ];then
    echo "$1 already exists." 
    exit 1
fi
mkdir $1
cd $1

mkdir data 
mkdir test 
mkdir dataset
touch dataset/__init__.py
mkdir -p experiments/logs 
mkdir -p experiments/scripts 

touch augmentation.py
touch models.py 
touch train.py 
touch predict.py 
touch README.md
