#!/bin/bash -e

cfg=".synccode.ini"
if [ ! -f $cfg ];then
    echo "please create .synccode.ini"
    exit
fi
src=$(basename `pwd`)
remote=`cat $cfg`

if [ "$(basename $remote)"x = "$src"x ];then
    remote=$(dirname $remote)
fi

cd ..
echo "$src/.git" >> $src/ignore_rsync
echo "$src/.*.swp" >> $src/ignore_rsync
echo "$src/.*.swo" >> $src/ignore_rsync
if [ -n "$1" ];then
    echo "$src/$1" >> $src/ignore_rsync
fi
rsync -avrztopg --progress --exclude-from $src/ignore_rsync $src $remote
rm $src/ignore_rsync
