#!/bin/bash -e

if hash tmux 2>/dev/null;then
    if [ ! -n "$1" ];then
        tmux list-sessions
        echo "tmuxb [sessionID]"
        exit 1
    else
        tmux attach-session -t $1
    fi
else
    echo 'tmux not found, please install tmux first.'
    exit
fi
